export const fakeFetch = (url) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (url === "https://example.com/api/doctors") {
        resolve({
          status: 200,
          message: "Success",
          data: {
            doctors: [
              {
                id: 1,
                name: "Dr. John Doe",
                specialty: "Cardiology",
                location: "New York, NY",
                rating: 4.8,
                phone: "(123) 456-7890",
                email: "johndoe@example.com",
              },
              {
                id: 2,
                name: "Dr. Jane Smith",
                specialty: "Dermatology",
                location: "Los Angeles, CA",
                rating: 4.7,
                phone: "(987) 654-3210",
                email: "janesmith@example.com",
              },
              {
                id: 3,
                name: "Dr. Emily Johnson",
                specialty: "Pediatrics",
                location: "Chicago, IL",
                rating: 4.9,
                phone: "(555) 123-4567",
                email: "emilyjohnson@example.com",
              },
              {
                id: 4,
                name: "Dr. Michael Brown",
                specialty: "Orthopedics",
                location: "Houston, TX",
                rating: 4.6,
                phone: "(713) 456-7890",
                email: "michaelbrown@example.com",
              },
              {
                id: 5,
                name: "Dr. Sarah Wilson",
                specialty: "Gynecology",
                location: "Phoenix, AZ",
                rating: 4.7,
                phone: "(602) 987-6543",
                email: "sarahwilson@example.com",
              },
              {
                id: 6,
                name: "Dr. David Lee",
                specialty: "Neurology",
                location: "Philadelphia, PA",
                rating: 4.8,
                phone: "(215) 345-6789",
                email: "davidlee@example.com",
              },
              {
                id: 7,
                name: "Dr. Jessica Taylor",
                specialty: "Psychiatry",
                location: "San Antonio, TX",
                rating: 4.5,
                phone: "(210) 765-4321",
                email: "jessicataylor@example.com",
              },
              {
                id: 8,
                name: "Dr. Robert Martinez",
                specialty: "Gastroenterology",
                location: "San Diego, CA",
                rating: 4.6,
                phone: "(619) 555-0123",
                email: "robertmartinez@example.com",
              },
              {
                id: 9,
                name: "Dr. Linda Hernandez",
                specialty: "Endocrinology",
                location: "Dallas, TX",
                rating: 4.7,
                phone: "(972) 555-6789",
                email: "lindahernandez@example.com",
              },
              {
                id: 10,
                name: "Dr. William Robinson",
                specialty: "Oncology",
                location: "Miami, FL",
                rating: 4.8,
                phone: "(305) 555-4321",
                email: "williamrobinson@example.com",
              },
              {
                id: 11,
                name: "Dr. Charles Wilson",
                specialty: "Cardiology",
                location: "Seattle, WA",
                rating: 4.9,
                phone: "(206) 555-0182",
                email: "charleswilson@example.com",
              },
              {
                id: 12,
                name: "Dr. Michelle Garcia",
                specialty: "Dermatology",
                location: "San Francisco, CA",
                rating: 4.7,
                phone: "(415) 555-0193",
                email: "michellegarcia@example.com",
              },
              {
                id: 13,
                name: "Dr. Kevin Lee",
                specialty: "Pediatrics",
                location: "Austin, TX",
                rating: 4.6,
                phone: "(512) 555-0144",
                email: "kevinlee@example.com",
              },
              {
                id: 14,
                name: "Dr. Laura Martinez",
                specialty: "Orthopedics",
                location: "Denver, CO",
                rating: 4.8,
                phone: "(720) 555-0175",
                email: "lauramartinez@example.com",
              },
              {
                id: 15,
                name: "Dr. Christopher Harris",
                specialty: "Gynecology",
                location: "Boston, MA",
                rating: 4.7,
                phone: "(617) 555-0186",
                email: "christopherharris@example.com",
              },
              {
                id: 16,
                name: "Dr. Nancy Thompson",
                specialty: "Neurology",
                location: "Las Vegas, NV",
                rating: 4.9,
                phone: "(702) 555-0127",
                email: "nancythompson@example.com",
              },
              {
                id: 17,
                name: "Dr. Brian White",
                specialty: "Psychiatry",
                location: "Orlando, FL",
                rating: 4.5,
                phone: "(321) 555-0148",
                email: "brianwhite@example.com",
              },
              {
                id: 18,
                name: "Dr. Karen Martin",
                specialty: "Gastroenterology",
                location: "Portland, OR",
                rating: 4.6,
                phone: "(503) 555-0159",
                email: "karenmartin@example.com",
              },
              {
                id: 19,
                name: "Dr. Ronald Lewis",
                specialty: "Endocrinology",
                location: "Atlanta, GA",
                rating: 4.7,
                phone: "(404) 555-0160",
                email: "ronaldlewis@example.com",
              },
              {
                id: 20,
                name: "Dr. Jennifer Walker",
                specialty: "Oncology",
                location: "Nashville, TN",
                rating: 4.8,
                phone: "(615) 555-0111",
                email: "jenniferwalker@example.com",
              },
              {
                id: 21,
                name: "Dr. Eric Young",
                specialty: "Cardiology",
                location: "Washington, DC",
                rating: 4.8,
                phone: "(202) 555-0122",
                email: "ericyoung@example.com",
              },
              {
                id: 22,
                name: "Dr. Jessica Hall",
                specialty: "Dermatology",
                location: "Philadelphia, PA",
                rating: 4.7,
                phone: "(215) 555-0133",
                email: "jessicahall@example.com",
              },
              {
                id: 23,
                name: "Dr. James Allen",
                specialty: "Pediatrics",
                location: "Phoenix, AZ",
                rating: 4.9,
                phone: "(602) 555-0144",
                email: "jamesallen@example.com",
              },
              {
                id: 24,
                name: "Dr. Sarah Scott",
                specialty: "Orthopedics",
                location: "San Diego, CA",
                rating: 4.6,
                phone: "(619) 555-0155",
                email: "sarahscott@example.com",
              },
              {
                id: 25,
                name: "Dr. William Green",
                specialty: "Gynecology",
                location: "Houston, TX",
                rating: 4.7,
                phone: "(713) 555-0166",
                email: "williamgreen@example.com",
              },
              {
                id: 26,
                name: "Dr. Patricia Adams",
                specialty: "Neurology",
                location: "Chicago, IL",
                rating: 4.8,
                phone: "(312) 555-0177",
                email: "patriciaadams@example.com",
              },
              {
                id: 27,
                name: "Dr. Charles Baker",
                specialty: "Psychiatry",
                location: "Los Angeles, CA",
                rating: 4.5,
                phone: "(310) 555-0188",
                email: "charlesbaker@example.com",
              },
              {
                id: 28,
                name: "Dr. Barbara Rodriguez",
                specialty: "Gastroenterology",
                location: "New York, NY",
                rating: 4.6,
                phone: "(212) 555-0199",
                email: "barbararodriguez@example.com",
              },
              {
                id: 29,
                name: "Dr. Daniel Lee",
                specialty: "Endocrinology",
                location: "San Francisco, CA",
                rating: 4.7,
                phone: "(415) 555-0100",
                email: "daniellee@example.com",
              },
              {
                id: 30,
                name: "Dr. Joseph Martinez",
                specialty: "Oncology",
                location: "Dallas, TX",
                rating: 4.8,
                phone: "(214) 555-0111",
                email: "josephmartinez@example.com",
              },
            ],
          },
        });
      } else {
        reject({
          status: 404,
          message: "doctors data not found.",
        });
      }
    }, 2000);
  });
};
